/**
 * Emits the $BRSR contract set into src/chain/generated/token.ts.
 *
 * @bursar/core generates the settlement contracts the same way and remains the source for those.
 * The token set landed after that codegen ran, so until core carries it this script reads the same
 * two inputs core reads: the compiled artifacts and the deployment records written by the deploys.
 * Nothing here is typed by hand.
 *
 *   pnpm --filter @bursar/web codegen:token
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

import { selectDeploymentRecords } from '@bursar/core';

const ROOT = resolve(import.meta.dirname, '../../..');
const DEPLOYMENTS = resolve(ROOT, 'contracts/deployments');
const OUT = resolve(import.meta.dirname, '../src/chain/generated/token.ts');
const CONTRACTS = ['BRSR', 'Vesting', 'Staking', 'Buyback'] as const;

type Record_ = {
  network: string;
  chainId: number;
  contracts: Record<string, string>;
  roles: Record<string, unknown>;
  supply: Record<string, string>;
};

/** The parts of a core record that name a redeployed token set. */
type CoreRecord = {
  network: string;
  chainId: number;
  supersedes?: string;
  contracts: Record<string, string>;
  token?: Record<string, unknown>;
  external?: Record<string, unknown>;
};

const record = JSON.parse(readFileSync(resolve(DEPLOYMENTS, 'rhc-mainnet-token.json'), 'utf8')) as Record_;

/**
 * The newest core record on the token's chain that deployed its own Staking and Buyback, which it
 * records under `token`. From v3 on the two are redeployed with the core set and answer to its
 * timelock; the token record still answers for the supply and whoever holds it.
 */
function successor(chainId: number): { name: string; json: CoreRecord } | undefined {
  const files = readdirSync(DEPLOYMENTS)
    .filter((file) => file.endsWith('.json'))
    .sort()
    .map((file) => ({ name: basename(file, '.json'), json: JSON.parse(readFileSync(resolve(DEPLOYMENTS, file), 'utf8')) as unknown }));
  const core = selectDeploymentRecords(files)
    .map((file) => ({ name: file.name, json: file.json as CoreRecord }))
    .filter((file) => file.json.chainId === chainId);

  let next = core.find((file) => !core.some((other) => other.json.supersedes === file.name));
  const seen = new Set<string>();
  while (next !== undefined && !seen.has(next.name)) {
    seen.add(next.name);
    const token = next.json.token;
    if (typeof token?.['Staking'] === 'string' && typeof token['Buyback'] === 'string') return next;
    const older = next.json.supersedes;
    next = older === undefined ? undefined : core.find((file) => file.name === older);
  }
  return undefined;
}

const newer = successor(record.chainId);
const overlay = (name: string, value: unknown): string | undefined => (typeof value === 'string' ? value : record.contracts[name]);

const addresses = [...CONTRACTS, 'PoolManager' as const].map((name) => {
  const value =
    newer === undefined
      ? record.contracts[name]
      : name === 'PoolManager'
        ? overlay(name, newer.json.external?.['PoolManager'])
        : overlay(name, newer.json.token?.[name]);
  if (!value) throw new Error(`${name} is missing from the token deployment record.`);
  return `  ${name}: '${value}',`;
});

// The community share sits with the token's governance delay, and moved with it when the delay was
// replaced; reading it at the first delay showed 80% of the supply held by nobody.
const followsTimelock = record.roles['community'] === record.roles['adminTimelock'];
const roles = (['adminTimelock', 'community', 'treasury', 'liquidity'] as const).map((name) => {
  const live = newer !== undefined && (name === 'adminTimelock' || (name === 'community' && followsTimelock));
  const value = live ? newer.json.contracts['AdminTimelock'] : record.roles[name];
  if (typeof value !== 'string') throw new Error(`roles.${name} is missing from the token deployment record.`);
  return `  ${name}: '${value}',`;
});

const abis = CONTRACTS.map((name) => {
  const artifact = JSON.parse(readFileSync(resolve(ROOT, `contracts/out/${name}.sol/${name}.json`), 'utf8')) as { abi: unknown };
  const key = `${name === 'BRSR' ? 'brsr' : name.charAt(0).toLowerCase() + name.slice(1)}Abi`;
  return `export const ${key} = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
});

const sources =
  newer === undefined
    ? 'contracts/deployments/rhc-mainnet-token.json'
    : `contracts/deployments/rhc-mainnet-token.json and\n// contracts/deployments/${newer.name}.json`;

writeFileSync(
  OUT,
  `// Generated by scripts/token-codegen.ts from contracts/out and
// ${sources}. Do not edit by hand.
// Regenerate with \`pnpm --filter @bursar/web codegen:token\`.
import type { Address } from 'viem';

export const TOKEN_CHAIN_ID = ${record.chainId};

export const TOKEN_ADDRESSES = {
${addresses.join('\n')}
} as const satisfies Readonly<Record<string, Address>>;

/** Who the record says holds each share of the supply, and the governance delay that administers the token contracts. */
export const TOKEN_ROLES = {
${roles.join('\n')}
} as const satisfies Readonly<Record<string, Address>>;

/** Fixed at construction and read back from chain at deploy. Eighteen decimals, wei. */
export const BRSR_SUPPLY = {
  total: ${record.supply['total']}n,
  community: ${record.supply['community']}n,
  team: ${record.supply['team']}n,
  treasury: ${record.supply['treasury']}n,
  liquidity: ${record.supply['liquidity']}n,
} as const;

${abis.join('\n\n')}
`,
  'utf8',
);

console.log(`Wrote ${OUT}${newer === undefined ? '' : `, with Staking and Buyback from ${newer.name}`}`);
