/**
 * Emits the $BRSR contract set into src/chain/generated/token.ts.
 *
 * @bursar/core generates the settlement contracts the same way and remains the source for those.
 * The token set landed after that codegen ran, so until core carries it this script reads the same
 * two inputs core reads: the compiled artifacts and the deployment record written by the deploy.
 * Nothing here is typed by hand.
 *
 *   pnpm --filter @bursar/web codegen:token
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../../..');
const OUT = resolve(import.meta.dirname, '../src/chain/generated/token.ts');
const CONTRACTS = ['BRSR', 'Vesting', 'Staking', 'Buyback'] as const;

type Record_ = {
  network: string;
  chainId: number;
  contracts: Record<string, string>;
  roles: Record<string, unknown>;
  supply: Record<string, string>;
};

const record = JSON.parse(readFileSync(resolve(ROOT, 'contracts/deployments/rhc-mainnet-token.json'), 'utf8')) as Record_;

const abis = CONTRACTS.map((name) => {
  const artifact = JSON.parse(readFileSync(resolve(ROOT, `contracts/out/${name}.sol/${name}.json`), 'utf8')) as { abi: unknown };
  const key = `${name === 'BRSR' ? 'brsr' : name.charAt(0).toLowerCase() + name.slice(1)}Abi`;
  return `export const ${key} = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
});

const addresses = CONTRACTS.concat('PoolManager' as never).map((name) => {
  const value = record.contracts[name];
  if (!value) throw new Error(`${name} is missing from the token deployment record.`);
  return `  ${name}: '${value}',`;
});

const roles = (['adminTimelock', 'community', 'treasury', 'liquidity'] as const).map((name) => {
  const value = record.roles[name];
  if (typeof value !== 'string') throw new Error(`roles.${name} is missing from the token deployment record.`);
  return `  ${name}: '${value}',`;
});

writeFileSync(
  OUT,
  `// Generated by scripts/token-codegen.ts from contracts/out and
// contracts/deployments/rhc-mainnet-token.json. Do not edit by hand.
// Regenerate with \`pnpm --filter @bursar/web codegen:token\`.
import type { Address } from 'viem';

export const TOKEN_CHAIN_ID = ${record.chainId};

export const TOKEN_ADDRESSES = {
${addresses.join('\n')}
} as const satisfies Readonly<Record<string, Address>>;

/** Who the record says holds each share of the supply, and the governance delay that administers the token contracts. */
export const TOKEN_ROLES = {
${roles.join('\n')}
} as const satisfies Readonly<Record<string, Address>>;

/** Fixed at construction and read back from chain at deploy. Eighteen decimals, wei. */
export const BRSR_SUPPLY = {
  total: ${record.supply['total']}n,
  community: ${record.supply['community']}n,
  team: ${record.supply['team']}n,
  treasury: ${record.supply['treasury']}n,
  liquidity: ${record.supply['liquidity']}n,
} as const;

${abis.join('\n\n')}
`,
  'utf8',
);

console.log(`Wrote ${OUT}`);
