/**
 * Writes contracts/test/fixtures/shielded.json: real proofs, made with the official Privacy Pools
 * artifacts, for the forge tests of ShieldedPool and ShieldedRelay. The addresses and the chain
 * id must match the ones test/shielded/Shielded.t.sol deploys to.
 *
 *   pnpm --filter @bursar/sdk exec tsx scripts/shielded-fixture.ts
 */
import { writeFileSync } from 'node:fs';

import { shieldedArtifacts } from '@bursar/circuits/privacy-pools';
import { getContractAddress, type Address, type Hex } from 'viem';

import {
  changeSecrets,
  depositSecrets,
  deriveShieldedKeys,
  encodeRelayData,
  labelOf,
  noteOf,
  precommitmentOf,
  scopeOf,
  withdrawalContext,
} from '../src/shielded.js';
import { proveRagequit, proveWithdrawal } from '../src/shielded-prove.js';

const CHAIN_ID = 4663;
const ASSET: Address = '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168';
// The test deploys each of these from its own pranked deployer at nonce 0.
const ENTRYPOINT = getContractAddress({ from: '0x00000000000000000000000000000000000e0001', nonce: 0n });
const POOL = getContractAddress({ from: '0x00000000000000000000000000000000000e0002', nonce: 0n });
const RELAY = getContractAddress({ from: '0x00000000000000000000000000000000000e0003', nonce: 0n });
const RECIPIENT: Address = '0x00000000000000000000000000000000000e0010';
const FEE_RECIPIENT: Address = '0x00000000000000000000000000000000000e0011';
const SIGNATURE: Hex = `0x${'ab'.repeat(32)}${'cd'.repeat(32)}1b`;

const keys = deriveShieldedKeys(SIGNATURE);
const scope = scopeOf(POOL, CHAIN_ID, ASSET);
const s1 = depositSecrets(keys, scope, 0n);
const s2 = depositSecrets(keys, scope, 1n);
const note1 = noteOf(1_000_000n, labelOf(scope, 1n), s1);
const note2 = noteOf(300_000n, labelOf(scope, 2n), s2);
const stateLeaves = [note1.commitment, note2.commitment];
const aspLabels = [note1.label, note2.label];
const data = encodeRelayData({ recipient: RECIPIENT, feeRecipient: FEE_RECIPIENT, relayFeeBPS: 100n });

async function withdrawVia(processooor: Address) {
  const withdrawal = { processooor, data };
  return proveWithdrawal({
    note: note1,
    amount: 400_000n,
    change: changeSecrets(keys, note1.label, 0n),
    stateLeaves,
    aspLabels,
    context: withdrawalContext(withdrawal, scope),
    artifacts: shieldedArtifacts.withdraw,
  });
}

console.time('withdraw');
const relayed = await withdrawVia(RELAY);
console.timeEnd('withdraw');
const viaEntrypoint = await withdrawVia(ENTRYPOINT);
const ragequit = await proveRagequit(note2, shieldedArtifacts.commitment);

const s = (v: bigint) => v.toString();
const proofJson = (p: { pA: readonly bigint[]; pB: readonly (readonly bigint[])[]; pC: readonly bigint[]; pubSignals: readonly bigint[] }) => ({
  pA: p.pA.map(s),
  pB: p.pB.map((r) => r.map(s)),
  pC: p.pC.map(s),
  pubSignals: p.pubSignals.map(s),
});

const fixture = {
  note: 'Generated by packages/sdk/scripts/shielded-fixture.ts with the Privacy Pools v1.3.0 ceremony keys.',
  chainId: CHAIN_ID,
  scope: s(scope),
  deposit1: { value: s(note1.value), precommitment: s(precommitmentOf(s1)), label: s(note1.label), commitment: s(note1.commitment) },
  deposit2: { value: s(note2.value), precommitment: s(precommitmentOf(s2)), label: s(note2.label), commitment: s(note2.commitment) },
  relayData: data,
  relayed: proofJson(relayed.proof),
  viaEntrypoint: proofJson(viaEntrypoint.proof),
  ragequit: proofJson(ragequit),
};
// Foundry's JSON parser reads large numbers as strings only when quoted; keep every value a string.
writeFileSync(new URL('../../../contracts/test/fixtures/shielded.json', import.meta.url), `${JSON.stringify(fixture, null, 2)}\n`);
console.log('fixture written; scope', s(scope));
// snarkjs leaves worker threads alive.
process.exit(0);
