/**
 * Writes shielded-e2e.json: real Privacy Pools v1.3.0 proofs for the shielded pool the deploy
 * scripts create in the end-to-end suite and in the local rehearsal.
 *
 * A proof is bound to its pool: the scope hashes the pool's address, the chain and the asset, and a
 * relayed withdrawal also names the relay. Both runs deploy from anvil's first account with the
 * nonce pinned to 10,000 before `DeployShielded.s.sol`, which creates every contract before it
 * calls anything, so the pool and the relay land at the two addresses below in both. Change the
 * script's creation order or the pinned nonce and these proofs stop verifying; rebuild them with
 *
 *   pnpm --filter @bursar/sdk exec tsx ../../contracts/test/script/fixtures/shielded-e2e.ts
 *
 * The deposits carry the deployment's 10 bps vetting fee, so 2.002002 and 1.001001 USDG in leave
 * notes of exactly 2 and 1 USDG. The note keys come from a fixed stand-in for a wallet signature:
 * the proofs need secrets that do not change between runs, not a wallet.
 */
import { writeFileSync } from 'node:fs';

import { shieldedArtifacts } from '../../../../circuits/privacy-pools.js';
import {
  changeSecrets,
  deriveLegacyShieldedKeys,
  depositSecrets,
  encodeRelayData,
  labelOf,
  noteOf,
  precommitmentOf,
  scopeOf,
  withdrawalContext,
} from '../../../../packages/sdk/src/shielded.js';
import { proveRagequit, proveWithdrawal } from '../../../../packages/sdk/src/shielded-prove.js';

const CHAIN_ID = 4663;
const ASSET = '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168';
// anvil's first account at nonces 10,004 and 10,005.
const POOL = '0xBe4c6d9139624c64fA34DBEB968fF61d1025b996';
const RELAY = '0x15556Bb9fAD25802bc4428F0008BA50A13807B57';
const RECIPIENT = '0x00000000000000000000000000000000000e2e10';
const FEE_RECIPIENT = '0x00000000000000000000000000000000000e2e11';
const RELAY_FEE_BPS = 100n;
const WITHDRAWN = 400_000n;
const SIGNATURE = `0x${'5e'.repeat(65)}` as const;

const keys = deriveLegacyShieldedKeys(SIGNATURE);
const scope = scopeOf(POOL, CHAIN_ID, ASSET);
const s1 = depositSecrets(keys, scope, 0n);
const s2 = depositSecrets(keys, scope, 1n);
const note1 = noteOf(2_000_000n, labelOf(scope, 1n), s1);
const note2 = noteOf(1_000_000n, labelOf(scope, 2n), s2);
const data = encodeRelayData({ recipient: RECIPIENT, feeRecipient: FEE_RECIPIENT, relayFeeBPS: RELAY_FEE_BPS });

const relayed = await proveWithdrawal({
  note: note1,
  amount: WITHDRAWN,
  change: changeSecrets(keys, note1.label, 0n),
  stateLeaves: [note1.commitment, note2.commitment],
  aspLabels: [note1.label, note2.label],
  context: withdrawalContext({ processooor: RELAY, data }, scope),
  artifacts: shieldedArtifacts.withdraw,
});
const ragequit = await proveRagequit(note2, shieldedArtifacts.commitment);

const s = (v: bigint) => v.toString();
const proofJson = (p: { pA: readonly bigint[]; pB: readonly (readonly bigint[])[]; pC: readonly bigint[]; pubSignals: readonly bigint[] }) => ({
  pA: p.pA.map(s),
  pB: p.pB.map((r) => r.map(s)),
  pC: p.pC.map(s),
  pubSignals: p.pubSignals.map(s),
});

const fixture = {
  note: 'Generated by test/script/fixtures/shielded-e2e.ts with the Privacy Pools v1.3.0 ceremony keys.',
  chainId: CHAIN_ID,
  pool: POOL,
  relay: RELAY,
  scope: s(scope),
  deposit1: { gross: '2002002', value: s(note1.value), precommitment: s(precommitmentOf(s1)), label: s(note1.label), commitment: s(note1.commitment) },
  deposit2: { gross: '1001001', value: s(note2.value), precommitment: s(precommitmentOf(s2)), label: s(note2.label), commitment: s(note2.commitment) },
  recipient: RECIPIENT,
  feeRecipient: FEE_RECIPIENT,
  relayFeeBps: s(RELAY_FEE_BPS),
  withdrawn: s(WITHDRAWN),
  relayData: data,
  relayed: proofJson(relayed.proof),
  ragequit: proofJson(ragequit),
};
// Foundry's JSON parser reads large numbers as strings only when quoted, so every figure is one.
writeFileSync(new URL('./shielded-e2e.json', import.meta.url), `${JSON.stringify(fixture, null, 2)}\n`);
console.log('fixture written; scope', s(scope));
// snarkjs leaves worker threads alive.
process.exit(0);
